[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
argon2 = {version = "0.6.0" }
axum = { version = "0.8.9", features = ["macros"] }
base64 = "0.23.1"
dotenvy = "0.15.7"
hex = "0.4.3"
jsonwebtoken = "11.0.0"
rand = "0.10.2"
rand_core = "0.10.1"
serde = {version = "1.0.229", features = ["derive"]}
serde_json = "1.0.151"
sha2 = "0.11.0"
sqlx = {version = "0.9.0", features = ["time", "uuid", "runtime-tokio", "postgres", "json", "tls-rustls-aws-lc-rs"]}
thiserror = "2.0.20"
time = {version = "0.3.55", features = ["serde"]}
tokio = {version = "1.53.1", features = ["full"]}
toml = "1.1.6"
tower = "0.5.3"
tower-http = "0.7.1"
tracing = "0.1.44"
utoipa = {version = "5.5.0", features = ["time", "uuid", "axum_extras"]}
utoipa-axum = "0.2.0"
utoipa-redoc = {version = "6.0.0", features = ["axum"]}
uuid = {version = "1.26.1", features = ["v4", "v7", "serde"]}

[build-dependencies]
dotenvy = "0.15.7"
sqlx = {version = "0.9.0", features = ["postgres"]}
tokio = {version = "1.53.1", features = ["macros", "rt-multi-thread"]}
